export const AccountStatus = {
	account: {
		now: "2022-06-14T10:46:32+00:00",
		uid: 1471535296,
		login: "music-bot-9mm",
		region: 225,
		fullName: "music-bot 9mm",
		secondName: "music-bot",
		firstName: "9mm",
		displayName: "music-bot-9mm",
		serviceAvailable: true,
		hostedUser: false,
		registeredAt: "2022-06-14T09:50:10+00:00",
	},
	permissions: {
		until: "2022-06-21T09:14:58+00:00",
		values: [
			"landing-play",
			"feed-play",
			"radio-play",
			"mix-play",
			"radio-skips",
			"play-radio-full-tracks",
		],
		default: [
			"landing-play",
			"feed-play",
			"radio-play",
			"mix-play",
			"play-radio-full-tracks",
		],
	},
	subscription: {
		hadAnySubscription: false,
		canStartTrial: false,
		mcdonalds: false,
	},
	subeditor: false,
	subeditorLevel: 0,
	pretrialActive: false,
	masterhub: {
		activeSubscriptions: [],
		availableSubscriptions: [],
	},
	plus: {
		hasPlus: false,
		isTutorialCompleted: false,
	},
	advertisement: "Оформите постоянную подписку – первый месяц бесплатно!",
	defaultEmail: "music-bot-9mm@yandex.ru",
	userhash: "9caa468a45d429e7ab190fa932d6496cef380d2c551746e5da1d3bac3171fcc4",
};

export const AccountSettings = {
	uid: 1471535296,
	lastFmScrobblingEnabled: false,
	facebookScrobblingEnabled: false,
	shuffleEnabled: false,
	addNewTrackOnPlaylistTop: false,
	volumePercents: 75,
	userMusicVisibility: "PUBLIC",
	userSocialVisibility: "PUBLIC",
	adsDisabled: true,
	modified: "2022-06-14T10:21:11Z",
	rbtDisabled: false,
	theme: "default",
	promosDisabled: false,
	autoPlayRadio: true,
	syncQueueEnabled: true,
	childModEnabled: false,
};
